### ISSUE TITLE
[MacOS] Csharprepl won't run after installation, unable to use it.

### ISSUE THREAD

**Issue by Sergiojoel9877** [waf/CSharpRepl#264]
### Version

0.6.1

### What happened?

After installing the pkg, I get this exception on the first (and subsequent) runs:

One or more errors occurred. (The type initializer for 
'CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver' 
threw an exception.)
Unhandled exception. System.TypeInitializationException: The type initializer for 'CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/hostfxr.dylib, 1): image not found
dlopen(/Users/sergiojoelferreras/.dotnet/tools/.store/csharprepl/0.6.1/csharprepl/0.6.1/tools/net7.0/any/hostfxr.dylib, 1): image not found
dlopen(hostfxr.dylib, 1): image not found
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libhostfxr.dylib, 1): image not found
dlopen(/Users/sergiojoelferreras/.dotnet/tools/.store/csharprepl/0.6.1/csharprepl/0.6.1/tools/net7.0/any/libhostfxr.dylib, 1): image not found
dlopen(libhostfxr.dylib, 1): image not found
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/hostfxr, 1): image not found
dlopen(/Users/sergiojoelferreras/.dotnet/tools/.store/csharprepl/0.6.1/csharprepl/0.6.1/tools/net7.0/any/hostfxr, 1): image not found
dlopen(hostfxr, 1): image not found
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libhostfxr, 1): image not found
dlopen(/Users/sergiojoelferreras/.dotnet/tools/.store/csharprepl/0.6.1/csharprepl/0.6.1/tools/net7.0/any/libhostfxr, 1): image not found
dlopen(libhostfxr, 1): image not found

   at Microsoft.Build.Locator.NativeMethods.hostfxr_resolve_sdk2(String exe_dir, String working_dir, hostfxr_resolve_sdk2_flags_t flags, hostfxr_resolve_sdk2_result_fn result)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver..cctor() in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\MetadataResolvers\SolutionFileMetadataResolver.cs:line 28
   --- End of inner exception stack trace ---
   at CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver..ctor(DotnetBuilder builder, IConsoleEx console) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\MetadataResolvers\SolutionFileMetadataResolver.cs:line 32
   at CSharpRepl.Services.Roslyn.Scripting.ScriptRunner..ctor(WorkspaceManager workspaceManager, CSharpCompilationOptions compilationOptions, AssemblyReferenceService referenceAssemblyService, IConsoleEx console, Configuration configuration) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\Scripting\ScriptRunner.cs:line 49
   at CSharpRepl.Services.Roslyn.RoslynServices.<>c__DisplayClass20_1.<.ctor>b__1() in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\RoslynServices.cs:line 92
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CSharpRepl.Services.Roslyn.RoslynServices.ShouldOpenCompletionWindowAsync(String text, Int32 caret, KeyPress keyPress, CancellationToken cancellationToken) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\RoslynServices.cs:line 257
   at PrettyPrompt.Panes.CompletionPane.PrettyPrompt.Consoles.IKeyPressHandler.OnKeyUp(KeyPress key, CancellationToken cancellationToken)
   at PrettyPrompt.Prompt.<>c__DisplayClass9_0.<<ReadLineAsync>g__InterpretKeyPress|0>d.MoveNext()
--- End of stack trace from previous location ---
   at PrettyPrompt.Prompt.ReadLineAsync()
   at CSharpRepl.ReadEvalPrintLoop.RunAsync(Configuration config) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\ReadEvalPrintLoop.cs:line 48
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 51
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 57
   at CSharpRepl.Program.<Main>(String[] args)
Abort trap: 6

Any ideas?

**Comment by Sergiojoel9877** [comment]
Finally found the libhostfxr.dylib, I have a local copy of the aspnetcore-runtime-2.1.30-osx-x64, inside of it I was able to locate it. Then pasting it into the .NET 7.0.5 directory solved the issue!!
