### ISSUE TITLE
No .NET SDKs were found

### ISSUE THREAD

**Issue by ivanjx** [waf/CSharpRepl#268]
### Version

0.6.1

### What happened?

```
~ 
❯ csharprepl 
Welcome to the C# REPL (Read Eval Print Loop)!
Type C# expressions and statements at the prompt and press Enter to evaluate 
them.
Type help to learn more, and type exit to quit.

> No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
One or more errors occurred. (The type initializer for 
'CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver' 
threw an exception.)

Unhandled exception. System.TypeInitializationException: The type initializer for 'CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver' threw an exception.
 ---> System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver..cctor() in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\MetadataResolvers\SolutionFileMetadataResolver.cs:line 28
   --- End of inner exception stack trace ---
   at CSharpRepl.Services.Roslyn.MetadataResolvers.SolutionFileMetadataResolver..ctor(DotnetBuilder builder, IConsoleEx console) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\MetadataResolvers\SolutionFileMetadataResolver.cs:line 32
   at CSharpRepl.Services.Roslyn.Scripting.ScriptRunner..ctor(WorkspaceManager workspaceManager, CSharpCompilationOptions compilationOptions, AssemblyReferenceService referenceAssemblyService, IConsoleEx console, Configuration configuration) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\Scripting\ScriptRunner.cs:line 49
   at CSharpRepl.Services.Roslyn.RoslynServices.<>c__DisplayClass20_1.<.ctor>b__1() in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\RoslynServices.cs:line 92
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CSharpRepl.Services.Roslyn.RoslynServices.EvaluateAsync(String input, String[] args, CancellationToken cancellationToken) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\RoslynServices.cs:line 106
   at CSharpRepl.ReadEvalPrintLoop.RunAsync(Configuration config) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\ReadEvalPrintLoop.cs:line 78
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 51
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 57
   at CSharpRepl.Program.<Main>(String[] args)
Aborted (core dumped)
```

```
~ 
❯ dotnet --list-sdks
7.0.304 [/snap/dotnet-sdk/210/sdk]
```

`dotnet build` command works fine. i am using ubuntu 23.04.

**Comment by Emik03** [comment]
While certainly a bug, have you checked if `DOTNET_ROOT` is exported?
Try `echo $DOTNET_ROOT`. It's possible you'll need to add the following line to your `.bashrc`:
```shell
export DOTNET_ROOT='/snap/dotnet-sdk/210'
```

**Comment by ivanjx** [comment]
it seems that the problem happens when the dotnet executable is placed on the other directory with `ln -s`. have to make sure that the dotnet root and the dotnet executable are inside the same directory. interestingly the other commands and packages work just fine.

**Comment by waf** [comment]
@ivanjx I see you've installed dotnet via a snap -- are you following the steps from https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap ?

When I follow those steps, including setting up the `DOTNET_ROOT` environment variable, then csharprepl works for me. If I don't set `DOTNET_ROOT` as suggested on that page, even the `dotnet` executable itself doesn't work.

After following those steps, `/usr/local/bin/dotnet` is a symlink to `/snap/dotnet-sdk/current/dotnet` .

Is the above setup different than yours? Thanks!

**Comment by ivanjx** [comment]
i set `DOTNET_ROOT=/snap/dotnet-sdk/current`. i already uninstalled the snap since dotnet watch doesn't work with it. i am now using dotnet via .tar.gz and it works normally.

**Comment by waf** [comment]
Thanks for confirming. At the very least, C# REPL shouldn't crash in this scenario. I'll use this issue to track cleaning up the behavior here. Thanks!

**Comment by waf** [comment]
I'm going to resolve this now. On the most recent release (v0.6.3), the REPL shouldn't crash when it finds this installation scenario. Thanks for reporting!
