### ISSUE TITLE
MainMethod_Version_ShowsVersion is flaky

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#307]
### Version

last

### What happened?

I've seen multiple times it failed.

```
2023-09-28T14:19:20.8370049Z [xUnit.net 00:00:01.15]       System.FormatException : The input string 'Writing trace log to C:\Users\runneradmin\AppData\Local\Temp\tmp3967' was not in a correct format.
2023-09-28T14:19:20.8370656Z [xUnit.net 00:00:01.15]       Stack Trace:
2023-09-28T14:19:20.8371400Z [xUnit.net 00:00:01.15]            at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
2023-09-28T14:19:20.8372394Z [xUnit.net 00:00:01.15]            at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
2023-09-28T14:19:20.8373375Z [xUnit.net 00:00:01.15]            at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
2023-09-28T14:19:20.8374010Z [xUnit.net 00:00:01.15]            at System.Version.Parse(String input)
2023-09-28T14:19:20.8374586Z [xUnit.net 00:00:01.15]            at System.Version..ctor(String version)
2023-09-28T14:19:20.8375680Z [xUnit.net 00:00:01.15]         D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Tests\ProgramTests.cs(34,0): at CSharpRepl.Tests.ProgramTests.MainMethod_Version_ShowsVersion()
2023-09-28T14:19:20.8376715Z [xUnit.net 00:00:01.15]         --- End of stack trace from previous location ---
2023-09-28T14:19:20.8377415Z   Passed CSharpRepl.Tests.TraceLoggerTests.Create_ThenLog_WritesToFile [2 ms]
2023-09-28T14:19:20.8378528Z   Passed CSharpRepl.Tests.CommandLineTests.ParseArguments_FrameworkArgument_SpecifiesFramework(flag: "/f") [7 ms]
2023-09-28T14:19:20.8379620Z   Passed CSharpRepl.Tests.CommandLineTests.ParseArguments_FrameworkArgument_SpecifiesFramework(flag: "-f") [1 ms]
2023-09-28T14:19:20.8380726Z   Passed CSharpRepl.Tests.CommandLineTests.ParseArguments_FrameworkArgument_SpecifiesFramework(flag: "--framework") [1 ms]
2023-09-28T14:19:20.8381796Z   Passed CSharpRepl.Tests.CommandLineTests.ParseArguments_HelpArguments_SpecifiesHelp(flag: "--help") [1 ms]
2023-09-28T14:19:20.8382675Z   Passed CSharpRepl.Tests.CommandLineTests.ParseArguments_HelpArguments_SpecifiesHelp(flag: "/h") [1 ms]
2023-09-28T14:19:20.8383490Z   Failed CSharpRepl.Tests.ProgramTests.MainMethod_Version_ShowsVersion [138 ms]
2023-09-28T14:19:20.8384201Z   Error Message:
2023-09-28T14:19:20.8385035Z    System.FormatException : The input string 'Writing trace log to C:\Users\runneradmin\AppData\Local\Temp\tmp3967' was not in a correct format.
2023-09-28T14:19:20.8385665Z   Stack Trace:
2023-09-28T14:19:20.8386320Z      at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
2023-09-28T14:19:20.8387252Z    at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
2023-09-28T14:19:20.8387970Z    at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
2023-09-28T14:19:20.8388601Z    at System.Version.Parse(String input)
2023-09-28T14:19:20.8389120Z    at System.Version..ctor(String version)
2023-09-28T14:19:20.8390081Z    at CSharpRepl.Tests.ProgramTests.MainMethod_Version_ShowsVersion() in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Tests\ProgramTests.cs:line 34
2023-09-28T14:19:20.8391002Z --- End of stack trace from previous location ---
```

**Comment by kindermannhubert** [comment]
I suppose it's colliding with `TraceLoggerTests`.
