### ISSUE TITLE
Pasting 🤦🏼‍♂️character into repl throws exception and exits repl

### ISSUE THREAD

**Issue by MikeSchurman** [waf/CSharpRepl#309]
### Version

0.6.5

### What happened?

I tried pasting the 🤦🏼‍♂️character into the repl and it throws an exception:

![image](https://github.com/waf/CSharpRepl/assets/7268923/156ea02c-1b74-4782-bbe2-f8aa8a6955ed)

```
> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.──────────────┬──────────────────┐
   at PrettyPrompt.Rendering.Screen.PositionCursor(Screen screen, ConsoleCoordinate cursor)
   at PrettyPrompt.Rendering.Screen..ctor(Int32 width, Int32 height, ConsoleCoordinate cursor, ScreenArea[] screenAreas) │
   at PrettyPrompt.Renderer.<RenderOutput>g__Redraw|7_0(<>c__DisplayClass7_0&)
   at PrettyPrompt.Renderer.RenderOutput(PromptResult result, CodePane codePane, OverloadPane overloadPane, CompletionPane completionPane, IReadOnlyCollection`1 highlights, KeyPress key)│ AppContext               │
   at PrettyPrompt.Prompt.RenderSyntaxHighlightedOutput(Renderer renderer, CodePane codePane, OverloadPane overloadPane, CompletionPane completionPane, KeyPress key, String inputText, PromptResult result)─────────┘
   at PrettyPrompt.Prompt.ReadLineAsync()
   at CSharpRepl.ReadEvalPrintLoop.RunAsync(Configuration config) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\ReadEvalPrintLoop.cs:line 49
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 68
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 74
   at CSharpRepl.Program.<Main>(String[] args)
   ```

**Comment by waf** [comment]
Thanks for reporting this! It was definitely working before, and I thought we even had good integration tests around this. I'll see what happened.

**Comment by waf** [comment]
Just a note for myself, 🤦🏼‍♂️ is composed of the following codepoints:

| Render | Codepoint | Name |
|--------|--------|--------|
| 🤦 | U+1F926| FACE PALM |
| 🏼 | U+1F3FC| EMOJI MODIFIER FITZPATRICK TYPE-3 |
| ‍ | U+200D | ZERO WIDTH JOINER |
| ♂ | U+2642| MALE SIGN |
|   | U+FE0F| VARIATION SELECTOR-16| 


I'm transferring this to the PrettyPrompt underlying library repository where it should be fixed.
