### ISSUE TITLE
Installing System.Automation.Management nuget package fails

### ISSUE THREAD

**Issue by amine-aboufirass** [waf/CSharpRepl#311]
### Version

0.6.5

### What happened?

Steps to reproduce:

- Start `csharprepl` 
- Run `#r "nuget: System.Management.Automation, 7.3.7"`

Following error occurs:

```
Could not find package 'System.Management.Automation'. Error: System.InvalidOperationException: Collection was modified; enumeration operation may not
execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.RenderLines() in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 136
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.LogMinimal(String data) in
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 74
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.Log(LogLevel level, String data) in
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 49
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.Log(ILogMessage message) in
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 40
   at NuGet.ProjectManagement.ConsoleProjectContext.Log(ILogMessage message)
   at NuGet.PackageManagement.ProjectContextLogger.Log(ILogMessage message)
   at NuGet.PackageManagement.PackagePreFetcher.LogFetchMessages(IEnumerable`1 fetchResults, String packagesFolderRoot, ILogger logger)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions,
INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions,
INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext
resolutionContext, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, IEnumerable`1 primarySources, IEnumerable`1
secondarySources, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext
resolutionContext, INuGetProjectContext nuGetProjectContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.DownloadPackageAsync(PackageIdentity packageIdentity, NuGetPackageManager packageManager,
ResolutionContext resolutionContext, IEnumerable`1 primarySourceRepositories, ISettings settings, CancellationToken cancellationToken) in
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 231
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.InstallAsync(String packageId, String version, CancellationToken cancellationToken) in
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 83
```

**Comment by kindermannhubert** [comment]
Looks like we need to add some locking into `ConsoleNugetLogger`. It's used from async methods.
