### ISSUE TITLE
Can't reference nuget packages in .rsp file

### ISSUE THREAD

**Issue by Sadra-jl** [waf/CSharpRepl#313]
### Version

0.6.5

### What happened?

tried to organize common Nuget packages in a response file as below:
```-r "nuget: Kurukuru"
-r "nuget: CliWrap"
-r "nuget: Humanizer"
-r "nuget: UnitsNet"
```

when feeding RELP with .rsp file it gets the following exceptions. 
using each references separately works fine.

<details><summary>Exceptions</summary>
<p>

```c#
Writing trace log to /home/sj13/Documents/source/scripts/csharprepl-tracelog-2023-10-15.txt

No applicable references were found inside 'Humanizer.Core.de.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.el.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.el.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.es.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.es.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.fa.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.fa.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.fi-FI.2.14.1' package.
No applicable references were found inside 'Humanizer.Core.fi-FI.2.14.1' package.
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
Could not find package 'UnitsNet'. Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.LogFinish(String text, Boolean success) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 105
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.InstallAsync(String packageId, String version, CancellationToken cancellationToken) in 
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 91
Could not find package 'CliWrap'. Error: System.ArgumentOutOfRangeException: Index was out of range. Mu
st be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.LogFinish(String text, Boolean success) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 105
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.InstallAsync(String packageId, String version, CancellationToken cancellationToken) in 
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 91
Could not find package 'Humanizer'. Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.RenderLines() in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 136
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.LogMinimal(String data) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 74
   at CSharpRepl.Services.Nuget.ConsoleNugetLogger.LogWarning(String data) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\ConsoleNugetLogger.cs:line 77
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.GetDependencies(NuGetFramework targetFramework, FolderNuGetProject nuGetProject, PackageIdentity packageIdentity, ManagedCodeConventions 
managedCodeConventions, Dictionary`2 aggregatedReferences, CancellationToken cancellationToken) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 187
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.GetDependencies(NuGetFramework targetFramework, FolderNuGetProject nuGetProject, PackageIdentity packageIdentity, ManagedCodeConventions 
managedCodeConventions, Dictionary`2 aggregatedReferences, CancellationToken cancellationToken) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 205
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.GetDependencies(NuGetFramework targetFramework, FolderNuGetProject nuGetProject, PackageIdentity packageIdentity, ManagedCodeConventions 
managedCodeConventions, CancellationToken cancellationToken) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 127
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.GetAssemblyReferenceWithDependencies(NuGetFramework targetFramework, FolderNuGetProject nuGetProject, PackageIdentity packageIdentity, CancellationToken 
cancellationToken) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 115
   at CSharpRepl.Services.Nuget.NugetPackageInstaller.InstallAsync(String packageId, String version, CancellationToken cancellationToken) in 
D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Nuget\NugetPackageInstaller.cs:line 88
┌────────────────────────────Exception────────────────────────────┐
│ Collection was modified; enumeration operation may not execute. │
└─────────────────────────────────────────────────────────────────┘

> 
``` 

</p>
</details> 

<details><summary>TraceLog</summary>
<p>

```c#
2023-10-15T18:16:43 - Trace session starting
2023-10-15T18:16:43 - Starting background initialization
2023-10-15T18:16:43 - Discovered dotnet version .NET Core SDK 7.0.111 at /usr/share/dotnet/sdk/7.0.111.
2023-10-15T18:16:43 - Available Reference Assemblies: "/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref": ["8.0.0-rc.2.23479.6", "7.0.11"]
2023-10-15T18:16:43 - Available Implementation Assemblies: "/usr/share/dotnet/shared/Microsoft.NETCore.App": ["8.0.0-rc.2.23479.6", "7.0.11"]
2023-10-15T18:16:43 - .NET Version: Microsoft.NETCore.App / 7.0.11
2023-10-15T18:16:43 - Reference Assembly Paths: /usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.11/ref/net7.0
2023-10-15T18:16:43 - Implementation Assembly Paths: /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11
2023-10-15T18:16:43 - Shared Framework Paths: /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11
2023-10-15T18:16:43 - Loaded Reference Assemblies: "/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.11/ref/net7.0": ["System.Xml.ReaderWriter.dll", "System.Diagnostics.TraceSource.dll", "System.Net.dll", "System.Net.WebSockets.dll", "System.Reflection.dll", "System.Net.NetworkInformation.dll", "System.Security.Claims.dll", "Microsoft.VisualBasic.dll", "System.IO.UnmanagedMemoryStream.dll", "System.Diagnostics.DiagnosticSource.dll", "System.IO.FileSystem.Primitives.dll", "System.Data.Common.dll", "System.Runtime.Numerics.dll", "System.IO.FileSystem.dll", "System.Windows.dll", "System.Configuration.dll", "System.Console.dll", "System.Xml.XDocument.dll", "System.Net.ServicePoint.dll", "System.Buffers.dll", "System.Runtime.Serialization.dll", "System.Threading.dll", "System.Security.Cryptography.dll", "System.Runtime.Serialization.Formatters.dll", "System.Text.Json.dll", "System.Net.NameResolution.dll", "Microsoft.Win32.Primitives.dll", "System.Drawing.Primitives.dll", "System.Collections.dll", "System.Security.dll", "System.Text.Encoding.dll", "System.Reflection.Metadata.dll", "System.Transactions.dll", "System.Formats.Tar.dll", "System.Xml.dll", "System.IO.FileSystem.AccessControl.dll", "System.Net.Ping.dll", "System.Collections.Immutable.dll", "System.Net.Http.Json.dll", "Microsoft.CSharp.dll", "System.Linq.dll", "System.ComponentModel.TypeConverter.dll", "System.ComponentModel.EventBasedAsync.dll", "System.Collections.NonGeneric.dll", "System.Runtime.Intrinsics.dll", "System.ObjectModel.dll", "System.Memory.dll", "System.Text.Encoding.CodePages.dll", "System.Linq.Queryable.dll", "System.dll", "System.Threading.Tasks.Extensions.dll", "System.Security.Cryptography.OpenSsl.dll", "System.Resources.Writer.dll", "System.Transactions.Local.dll", "System.IO.Compression.ZipFile.dll", "System.Net.Requests.dll", "System.Net.HttpListener.dll", "System.Net.WebProxy.dll", "System.Security.Cryptography.Cng.dll", "System.Threading.ThreadPool.dll", "System.Diagnostics.FileVersionInfo.dll", "System.Text.RegularExpressions.dll", "System.Runtime.Handles.dll", "Microsoft.Win32.Registry.dll", "System.Xml.XPath.XDocument.dll", "System.Collections.Specialized.dll", "System.Resources.ResourceManager.dll", "System.Xml.XmlDocument.dll", "System.Numerics.Vectors.dll", "System.Runtime.InteropServices.dll", "System.Net.Http.dll", "System.Security.Cryptography.Encoding.dll", "System.IO.dll", "System.IO.FileSystem.Watcher.dll", "System.Xml.Linq.dll", "System.Dynamic.Runtime.dll", "System.Collections.Concurrent.dll", "System.ComponentModel.Annotations.dll", "System.Diagnostics.Tools.dll", "System.Reflection.Emit.Lightweight.dll", "System.Runtime.dll", "System.Threading.Tasks.Dataflow.dll", "System.Runtime.InteropServices.JavaScript.dll", "System.Security.Cryptography.Primitives.dll", "System.Security.Principal.Windows.dll", "System.Runtime.Extensions.dll", "System.Runtime.CompilerServices.Unsafe.dll", "System.Reflection.Emit.dll", "System.Threading.Channels.dll", "System.Core.dll", "System.Linq.Expressions.dll", "System.Net.Security.dll", "System.Text.Encoding.Extensions.dll", "System.Threading.Overlapped.dll", "System.Globalization.dll", "System.Xml.XPath.dll", "System.Data.dll", "System.Reflection.DispatchProxy.dll", "System.Net.Mail.dll", "System.Globalization.Calendars.dll", "System.ComponentModel.Primitives.dll", "System.Globalization.Extensions.dll", "System.Net.WebClient.dll", "System.Resources.Reader.dll", "System.ComponentModel.dll", "System.IO.Compression.Brotli.dll", "System.Xml.XmlSerializer.dll", "System.Net.Sockets.dll", "System.Threading.Tasks.Parallel.dll", "netstandard.dll", "System.Net.Quic.dll", "System.Reflection.Primitives.dll", "System.ServiceProcess.dll", "System.Web.HttpUtility.dll", "System.Threading.Timer.dll", "System.Security.SecureString.dll", "System.Runtime.CompilerServices.VisualC.dll", "System.Security.AccessControl.dll", "System.Diagnostics.Tracing.dll", "System.Runtime.Serialization.Json.dll", "System.Reflection.Extensions.dll", "System.IO.Compression.dll", "System.Security.Cryptography.Csp.dll", "System.Threading.Thread.dll", "System.ValueTuple.dll", "System.Reflection.TypeExtensions.dll", "System.Net.WebHeaderCollection.dll", "Microsoft.VisualBasic.Core.dll", "System.IO.MemoryMappedFiles.dll", "System.Web.dll", "System.Linq.Parallel.dll", "System.Net.Primitives.dll", "System.Diagnostics.Contracts.dll", "System.Xml.Serialization.dll", "System.IO.Pipes.dll", "System.AppContext.dll", "System.IO.FileSystem.DriveInfo.dll", "System.IO.Compression.FileSystem.dll", "System.Threading.Tasks.dll", "System.ComponentModel.DataAnnotations.dll", "System.Security.Principal.dll", "System.Net.WebSockets.Client.dll", "System.Security.Cryptography.Algorithms.dll", "System.Text.Encodings.Web.dll", "System.Diagnostics.StackTrace.dll", "mscorlib.dll", "System.IO.Pipes.AccessControl.dll", "System.Drawing.dll", "System.Diagnostics.Process.dll", "WindowsBase.dll", "System.Runtime.InteropServices.RuntimeInformation.dll", "System.Diagnostics.TextWriterTraceListener.dll", "System.Numerics.dll", "System.Data.DataSetExtensions.dll", "System.Runtime.Loader.dll", "System.Diagnostics.Debug.dll", "System.Runtime.Serialization.Primitives.dll", "System.Formats.Asn1.dll", "System.Reflection.Emit.ILGeneration.dll", "System.Runtime.Serialization.Xml.dll", "System.Security.Cryptography.X509Certificates.dll", "System.ServiceModel.Web.dll", "System.IO.IsolatedStorage.dll"]
2023-10-15T18:16:43 - Loaded Implementation Assemblies: "/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.11": ["System.Reflection.Emit.Lightweight.dll", "System.Globalization.Extensions.dll", "System.Xml.ReaderWriter.dll", "System.Resources.Reader.dll", "System.Net.dll", "System.IO.Compression.Brotli.dll", "System.Reflection.dll", "System.Net.Sockets.dll", "System.Security.Claims.dll", "netstandard.dll", "System.IO.UnmanagedMemoryStream.dll", "System.Reflection.Primitives.dll", "System.IO.FileSystem.Primitives.dll", "System.Web.HttpUtility.dll", "System.Runtime.Numerics.dll", "System.Security.SecureString.dll", "System.Windows.dll", "System.Security.AccessControl.dll", "System.Console.dll", "System.Private.Xml.dll", "System.Net.ServicePoint.dll", "System.Runtime.Serialization.Json.dll", "System.Runtime.Serialization.dll", "System.IO.Compression.dll", "System.Security.Cryptography.dll", "System.Threading.Thread.dll", "System.Text.Json.dll", "System.Reflection.TypeExtensions.dll", "Microsoft.Win32.Primitives.dll", "Microsoft.VisualBasic.Core.dll", "System.Collections.dll", "System.Web.dll", "System.Text.Encoding.dll", "System.Net.Primitives.dll", "System.Transactions.dll", "System.Xml.Serialization.dll", "System.Xml.dll", "System.AppContext.dll", "System.Net.Ping.dll", "System.IO.Compression.FileSystem.dll", "System.Net.Http.Json.dll", "System.ComponentModel.DataAnnotations.dll", "System.Diagnostics.TraceSource.dll", "System.ServiceModel.Web.dll", "System.Net.WebSockets.dll", "System.IO.IsolatedStorage.dll", "System.Net.NetworkInformation.dll", "System.Runtime.dll", "Microsoft.VisualBasic.dll", "System.Threading.Tasks.Dataflow.dll", "System.Diagnostics.DiagnosticSource.dll", "System.Runtime.InteropServices.JavaScript.dll", "System.Data.Common.dll", "System.Security.Cryptography.Primitives.dll", "System.IO.FileSystem.dll", "System.Security.Principal.Windows.dll", "System.Configuration.dll", "System.Runtime.Extensions.dll", "System.Xml.XDocument.dll", "System.Runtime.CompilerServices.Unsafe.dll", "System.Buffers.dll", "System.Reflection.Emit.dll", "System.Threading.dll", "System.Threading.Channels.dll", "System.Runtime.Serialization.Formatters.dll", "System.Core.dll", "System.Net.NameResolution.dll", "System.Linq.Expressions.dll", "System.Drawing.Primitives.dll", "System.Net.Security.dll", "System.Security.dll", "System.Text.Encoding.Extensions.dll", "System.Reflection.Metadata.dll", "System.Threading.Overlapped.dll", "System.Private.Xml.Linq.dll", "System.Globalization.dll", "System.Formats.Tar.dll", "System.Xml.XPath.dll", "System.IO.FileSystem.AccessControl.dll", "System.Data.dll", "System.Collections.Immutable.dll", "System.Reflection.DispatchProxy.dll", "Microsoft.CSharp.dll", "System.Net.Mail.dll", "System.Net.WebSockets.Client.dll", "System.Security.Cryptography.Algorithms.dll", "System.Text.Encodings.Web.dll", "System.Diagnostics.StackTrace.dll", "mscorlib.dll", "System.IO.Pipes.AccessControl.dll", "System.Drawing.dll", "System.Diagnostics.Process.dll", "WindowsBase.dll", "System.Runtime.InteropServices.RuntimeInformation.dll", "System.Diagnostics.TextWriterTraceListener.dll", "System.Private.CoreLib.dll", "System.Numerics.dll", "System.Data.DataSetExtensions.dll", "System.Runtime.Loader.dll", "System.Diagnostics.Debug.dll", "System.Runtime.Serialization.Primitives.dll", "System.Formats.Asn1.dll", "System.Reflection.Emit.ILGeneration.dll", "System.Runtime.Serialization.Xml.dll", "System.Security.Cryptography.X509Certificates.dll", "System.Globalization.Calendars.dll", "System.ComponentModel.Primitives.dll", "System.Net.WebClient.dll", "System.ComponentModel.dll", "System.Xml.XmlSerializer.dll", "System.Threading.Tasks.Parallel.dll", "System.Net.Quic.dll", "System.ServiceProcess.dll", "System.Threading.Timer.dll", "System.Runtime.CompilerServices.VisualC.dll", "System.Diagnostics.Tracing.dll", "System.Reflection.Extensions.dll", "System.Security.Cryptography.Csp.dll", "System.ValueTuple.dll", "System.Net.WebHeaderCollection.dll", "System.IO.MemoryMappedFiles.dll", "System.Linq.Parallel.dll", "System.Diagnostics.Contracts.dll", "System.IO.Pipes.dll", "System.IO.FileSystem.DriveInfo.dll", "System.Threading.Tasks.dll", "System.Linq.dll", "System.ComponentModel.TypeConverter.dll", "System.ComponentModel.EventBasedAsync.dll", "System.Collections.NonGeneric.dll", "System.Runtime.Intrinsics.dll", "System.ObjectModel.dll", "System.Memory.dll", "System.Text.Encoding.CodePages.dll", "System.Linq.Queryable.dll", "System.dll", "System.Private.Uri.dll", "System.Threading.Tasks.Extensions.dll", "System.Security.Cryptography.OpenSsl.dll", "System.Resources.Writer.dll", "System.Transactions.Local.dll", "System.IO.Compression.ZipFile.dll", "System.Net.Requests.dll", "System.Net.HttpListener.dll", "System.Net.WebProxy.dll", "System.Security.Cryptography.Cng.dll", "System.Threading.ThreadPool.dll", "System.Private.DataContractSerialization.dll", "System.Security.Principal.dll", "System.Diagnostics.FileVersionInfo.dll", "System.Text.RegularExpressions.dll", "System.Runtime.Handles.dll", "Microsoft.Win32.Registry.dll", "System.Xml.XPath.XDocument.dll", "System.Collections.Specialized.dll", "System.Resources.ResourceManager.dll", "System.Xml.XmlDocument.dll", "System.Numerics.Vectors.dll", "System.Runtime.InteropServices.dll", "System.Net.Http.dll", "System.Security.Cryptography.Encoding.dll", "System.IO.dll", "System.IO.FileSystem.Watcher.dll", "System.Xml.Linq.dll", "System.Dynamic.Runtime.dll", "System.Collections.Concurrent.dll", "System.ComponentModel.Annotations.dll", "System.Diagnostics.Tools.dll"]
2023-10-15T18:16:44 - MEF Default Assemblies: /home/sj13/.dotnet/tools/.store/csharprepl/0.6.5/csharprepl/0.6.5/tools/net7.0/any/Microsoft.CodeAnalysis.Workspaces.dll, /home/sj13/.dotnet/tools/.store/csharprepl/0.6.5/csharprepl/0.6.5/tools/net7.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll, /home/sj13/.dotnet/tools/.store/csharprepl/0.6.5/csharprepl/0.6.5/tools/net7.0/any/Microsoft.CodeAnalysis.Features.dll, /home/sj13/.dotnet/tools/.store/csharprepl/0.6.5/csharprepl/0.6.5/tools/net7.0/any/Microsoft.CodeAnalysis.CSharp.Features.dll
2023-10-15T18:16:44 - Background initialization complete
``` 

</p>
</details>

**Comment by waf** [comment]
This is mostly fixed by https://github.com/waf/CSharpRepl/pull/322

When multiple packages are loaded at once, the nuget logger is run concurrently, causing the errors due to its fancy output rendering. The above PR fixes those errors by introducing some locking.

I'm not going to mark this issue as resolved quite yet, because even though there are no longer any errors, the output is quite misleading. The 3 threads (due to the 3 nuget references) are trying to write lines and clear lines separately, and they're stepping on each other. I have some ideas on how to fix this.

**Comment by waf** [comment]
Fixed in the latest `main` branch. I'll get a release out this weekend.
