### ISSUE TITLE
Crash when typing `new Script`

### ISSUE THREAD

**Issue by Emik03** [waf/CSharpRepl#359]
### Version

C# REPL 0.6.7+d2955f13e744320cd6331c484e1286c3ed4f8612

### What happened?

In a new instance of C# REPL, type `new Script`. The `t` keystroke causes a crash.

<details>
<summary>Trace</summary>

```
2024-04-20T18:33:52 - Trace session starting
2024-04-20T18:33:52 - Starting background initialization
2024-04-20T18:33:52 - Discovered dotnet version .NET Core SDK 8.0.204 at /home/emik/.dotnet/sdk/8.0.204.
2024-04-20T18:33:52 - Available Reference Assemblies: "/home/emik/.dotnet/packs/Microsoft.NETCore.App.Ref": ["9.0.0-preview.2.24128.5", "5.0.0", "6.0.29", "7.0.18", "8.0.4", "9.0.0-preview.3.24172.9"]
2024-04-20T18:33:52 - Available Implementation Assemblies: "/home/emik/.dotnet/shared/Microsoft.NETCore.App": ["9.0.0-preview.2.24128.5", "5.0.17", "6.0.29", "7.0.18", "8.0.4", "9.0.0-preview.3.24172.9"]
2024-04-20T18:33:52 - .NET Version: Microsoft.NETCore.App / 8.0.4
2024-04-20T18:33:52 - Reference Assembly Paths: /home/emik/.dotnet/packs/Microsoft.NETCore.App.Ref/8.0.4/ref/net8.0
2024-04-20T18:33:52 - Implementation Assembly Paths: /home/emik/.dotnet/shared/Microsoft.NETCore.App/8.0.4
2024-04-20T18:33:52 - Shared Framework Paths: /home/emik/.dotnet/shared/Microsoft.NETCore.App/8.0.4
2024-04-20T18:33:52 - Loaded Reference Assemblies: "/home/emik/.dotnet/packs/Microsoft.NETCore.App.Ref/8.0.4/ref/net8.0": ["System.Numerics.dll", "System.Security.Cryptography.Primitives.dll", "System.IO.MemoryMappedFiles.dll", "System.Collections.Specialized.dll", "System.Security.dll", "System.ObjectModel.dll", "System.Net.dll", "System.IO.UnmanagedMemoryStream.dll", "System.Runtime.Serialization.dll", "System.Threading.Tasks.Extensions.dll", "System.Xml.XmlSerializer.dll", "System.IO.Compression.dll", "System.ServiceModel.Web.dll", "Microsoft.CSharp.dll", "System.Net.NameResolution.dll", "System.AppContext.dll", "System.Net.WebSockets.Client.dll", "System.Security.Cryptography.X509Certificates.dll", "System.Threading.Overlapped.dll", "System.Memory.dll", "System.Data.dll", "System.Security.Principal.Windows.dll", "System.Text.Encoding.Extensions.dll", "System.IO.Compression.FileSystem.dll", "System.Net.Ping.dll", "System.Threading.Tasks.dll", "System.Formats.Asn1.dll", "System.Resources.Reader.dll", "System.Security.Principal.dll", "System.IO.FileSystem.Primitives.dll", "System.Security.AccessControl.dll", "System.Runtime.CompilerServices.VisualC.dll", "System.Xml.XPath.dll", "System.Collections.Immutable.dll", "System.Dynamic.Runtime.dll", "System.Globalization.Extensions.dll", "System.Text.Encoding.CodePages.dll", "System.IO.FileSystem.AccessControl.dll", "System.IO.Pipes.dll", "System.Runtime.Serialization.Json.dll", "System.Buffers.dll", "System.Threading.Thread.dll", "System.Runtime.InteropServices.dll", "netstandard.dll", "System.Core.dll", "System.Diagnostics.FileVersionInfo.dll", "System.Net.ServicePoint.dll", "System.Threading.Channels.dll", "System.Security.Cryptography.OpenSsl.dll", "System.Reflection.DispatchProxy.dll", "System.Transactions.dll", "System.Reflection.Primitives.dll", "System.Runtime.Numerics.dll", "System.Runtime.Serialization.Formatters.dll", "Microsoft.VisualBasic.dll", "System.Threading.dll", "System.Xml.XmlDocument.dll", "System.ValueTuple.dll", "System.Net.Primitives.dll", "System.IO.Pipes.AccessControl.dll", "System.Runtime.Serialization.Xml.dll", "System.Runtime.InteropServices.JavaScript.dll", "System.Net.Http.Json.dll", "mscorlib.dll", "System.Linq.Parallel.dll", "System.Net.WebHeaderCollection.dll", "System.ComponentModel.dll", "System.Runtime.Handles.dll", "System.Threading.Tasks.Dataflow.dll", "Microsoft.Win32.Registry.dll", "System.Security.Cryptography.Encoding.dll", "System.Text.Json.dll", "System.Diagnostics.Contracts.dll", "System.ComponentModel.Primitives.dll", "System.Security.Cryptography.Algorithms.dll", "System.Reflection.Emit.Lightweight.dll", "Microsoft.VisualBasic.Core.dll", "System.Net.Quic.dll", "System.Security.Claims.dll", "System.IO.Compression.ZipFile.dll", "System.Resources.Writer.dll", "System.Windows.dll", "System.Globalization.dll", "System.Security.Cryptography.dll", "System.Diagnostics.Tracing.dll", "System.Configuration.dll", "System.Web.HttpUtility.dll", "System.Xml.XDocument.dll", "System.Diagnostics.DiagnosticSource.dll", "System.Text.Encoding.dll", "System.ServiceProcess.dll", "System.Net.WebProxy.dll", "System.Collections.NonGeneric.dll", "System.Net.Sockets.dll", "System.IO.FileSystem.Watcher.dll", "System.Xml.Serialization.dll", "System.Reflection.Emit.dll", "System.Xml.XPath.XDocument.dll", "System.dll", "System.Security.Cryptography.Cng.dll", "System.Net.Security.dll", "System.Console.dll", "System.Security.Cryptography.Csp.dll", "System.Drawing.Primitives.dll", "WindowsBase.dll", "System.IO.FileSystem.dll", "System.Linq.dll", "System.Net.Http.dll", "System.Resources.ResourceManager.dll", "System.Text.RegularExpressions.dll", "System.Runtime.Serialization.Primitives.dll", "System.ComponentModel.Annotations.dll", "System.Diagnostics.TraceSource.dll", "System.Globalization.Calendars.dll", "System.Xml.ReaderWriter.dll", "System.ComponentModel.TypeConverter.dll", "System.Linq.Expressions.dll", "System.Collections.Concurrent.dll", "System.Data.DataSetExtensions.dll", "System.IO.Compression.Brotli.dll", "System.Collections.dll", "Microsoft.Win32.Primitives.dll", "System.Reflection.dll", "System.Net.Requests.dll", "System.Runtime.Extensions.dll", "System.Diagnostics.StackTrace.dll", "System.Diagnostics.Debug.dll", "System.Net.Mail.dll", "System.Drawing.dll", "System.Linq.Queryable.dll", "System.Reflection.Emit.ILGeneration.dll", "System.Data.Common.dll", "System.ComponentModel.EventBasedAsync.dll", "System.Runtime.CompilerServices.Unsafe.dll", "System.Threading.ThreadPool.dll", "System.Runtime.InteropServices.RuntimeInformation.dll", "System.Web.dll", "System.Reflection.TypeExtensions.dll", "System.Threading.Timer.dll", "System.Transactions.Local.dll", "System.Runtime.dll", "System.IO.IsolatedStorage.dll", "System.Runtime.Loader.dll", "System.Formats.Tar.dll", "System.Security.SecureString.dll", "System.Threading.Tasks.Parallel.dll", "System.Diagnostics.TextWriterTraceListener.dll", "System.Text.Encodings.Web.dll", "System.Reflection.Extensions.dll", "System.Xml.Linq.dll", "System.Net.WebSockets.dll", "System.ComponentModel.DataAnnotations.dll", "System.Diagnostics.Tools.dll", "System.Runtime.Intrinsics.dll", "System.IO.dll", "System.Numerics.Vectors.dll", "System.Reflection.Metadata.dll", "System.Net.WebClient.dll", "System.Xml.dll", "System.Net.NetworkInformation.dll", "System.Diagnostics.Process.dll", "System.Net.HttpListener.dll", "System.IO.FileSystem.DriveInfo.dll"]
2024-04-20T18:33:52 - Loaded Implementation Assemblies: "/home/emik/.dotnet/shared/Microsoft.NETCore.App/8.0.4": ["System.Runtime.InteropServices.RuntimeInformation.dll", "System.Net.NameResolution.dll", "System.AppContext.dll", "System.Net.WebSockets.Client.dll", "System.Security.Cryptography.X509Certificates.dll", "System.Threading.Overlapped.dll", "System.Memory.dll", "System.Data.dll", "System.Security.Principal.Windows.dll", "System.Text.Encoding.Extensions.dll", "System.Private.Uri.dll", "System.IO.Compression.FileSystem.dll", "System.Net.Ping.dll", "System.Threading.Tasks.dll", "System.Formats.Asn1.dll", "System.Resources.Reader.dll", "System.Numerics.dll", "System.Security.Cryptography.Primitives.dll", "System.IO.MemoryMappedFiles.dll", "System.Collections.Specialized.dll", "System.Security.dll", "System.ObjectModel.dll", "System.Net.dll", "System.IO.UnmanagedMemoryStream.dll", "System.Runtime.Serialization.dll", "System.Threading.Tasks.Extensions.dll", "System.Xml.XmlSerializer.dll", "System.IO.Compression.dll", "System.Runtime.Handles.dll", "System.Net.WebSockets.dll", "System.ComponentModel.DataAnnotations.dll", "System.Diagnostics.Tools.dll", "System.Runtime.Intrinsics.dll", "System.IO.dll", "System.Numerics.Vectors.dll", "System.Reflection.Metadata.dll", "System.Net.WebClient.dll", "System.Xml.dll", "System.Net.NetworkInformation.dll", "System.Diagnostics.Process.dll", "System.Net.HttpListener.dll", "System.IO.FileSystem.DriveInfo.dll", "System.Runtime.Serialization.Formatters.dll", "Microsoft.VisualBasic.dll", "System.Xml.Serialization.dll", "System.Reflection.Emit.dll", "System.Xml.XPath.XDocument.dll", "System.dll", "System.Security.Cryptography.Cng.dll", "System.Net.Security.dll", "System.Console.dll", "System.Security.Cryptography.Csp.dll", "System.Drawing.Primitives.dll", "WindowsBase.dll", "System.IO.FileSystem.dll", "System.Linq.dll", "System.Security.Principal.dll", "System.IO.FileSystem.Primitives.dll", "System.Security.AccessControl.dll", "System.Runtime.CompilerServices.VisualC.dll", "System.Xml.XPath.dll", "System.Collections.Immutable.dll", "System.Dynamic.Runtime.dll", "System.Globalization.Extensions.dll", "System.Text.Encoding.CodePages.dll", "System.IO.FileSystem.AccessControl.dll", "System.IO.Pipes.dll", "System.Runtime.Serialization.Json.dll", "System.Buffers.dll", "System.Threading.Thread.dll", "System.Xml.Linq.dll", "System.Windows.dll", "System.Globalization.dll", "System.Security.Cryptography.dll", "System.Diagnostics.Tracing.dll", "System.Configuration.dll", "System.Web.HttpUtility.dll", "System.Xml.XDocument.dll", "System.Diagnostics.DiagnosticSource.dll", "System.Text.Encoding.dll", "System.ServiceProcess.dll", "System.Net.WebProxy.dll", "System.Collections.NonGeneric.dll", "System.Net.Sockets.dll", "System.ServiceModel.Web.dll", "Microsoft.CSharp.dll", "System.Runtime.InteropServices.dll", "netstandard.dll", "System.Core.dll", "System.Diagnostics.FileVersionInfo.dll", "System.Private.DataContractSerialization.dll", "System.Net.ServicePoint.dll", "System.Threading.Channels.dll", "System.Security.Cryptography.OpenSsl.dll", "System.Reflection.DispatchProxy.dll", "System.Transactions.dll", "System.Reflection.Primitives.dll", "System.Runtime.Numerics.dll", "System.IO.FileSystem.Watcher.dll", "System.Reflection.dll", "System.Net.Requests.dll", "System.Runtime.Extensions.dll", "System.Diagnostics.StackTrace.dll", "System.Diagnostics.Debug.dll", "System.Net.Mail.dll", "System.Drawing.dll", "System.Linq.Queryable.dll", "System.Reflection.Emit.ILGeneration.dll", "System.Data.Common.dll", "System.ComponentModel.EventBasedAsync.dll", "System.Runtime.CompilerServices.Unsafe.dll", "System.Threading.ThreadPool.dll", "System.Resources.ResourceManager.dll", "System.Text.RegularExpressions.dll", "System.Runtime.Serialization.Primitives.dll", "System.ComponentModel.Annotations.dll", "System.Diagnostics.TraceSource.dll", "System.Globalization.Calendars.dll", "System.Xml.ReaderWriter.dll", "System.ComponentModel.TypeConverter.dll", "System.Linq.Expressions.dll", "System.Collections.Concurrent.dll", "System.Data.DataSetExtensions.dll", "System.IO.Compression.Brotli.dll", "System.Collections.dll", "Microsoft.Win32.Primitives.dll", "System.Net.Http.dll", "System.Threading.Tasks.Dataflow.dll", "Microsoft.Win32.Registry.dll", "System.Security.Cryptography.Encoding.dll", "System.Text.Json.dll", "System.Diagnostics.Contracts.dll", "System.ComponentModel.Primitives.dll", "System.Security.Cryptography.Algorithms.dll", "System.Reflection.Emit.Lightweight.dll", "Microsoft.VisualBasic.Core.dll", "System.Net.Quic.dll", "System.Security.Claims.dll", "System.IO.Compression.ZipFile.dll", "System.Resources.Writer.dll", "System.Private.Xml.Linq.dll", "System.Threading.dll", "System.Xml.XmlDocument.dll", "System.ValueTuple.dll", "System.Net.Primitives.dll", "System.Private.Xml.dll", "System.IO.Pipes.AccessControl.dll", "System.Runtime.Serialization.Xml.dll", "System.Runtime.InteropServices.JavaScript.dll", "System.Net.Http.Json.dll", "mscorlib.dll", "System.Linq.Parallel.dll", "System.Net.WebHeaderCollection.dll", "System.ComponentModel.dll", "System.Private.CoreLib.dll", "System.Web.dll", "System.Reflection.TypeExtensions.dll", "System.Threading.Timer.dll", "System.Transactions.Local.dll", "System.Runtime.dll", "System.IO.IsolatedStorage.dll", "System.Runtime.Loader.dll", "System.Formats.Tar.dll", "System.Security.SecureString.dll", "System.Threading.Tasks.Parallel.dll", "System.Diagnostics.TextWriterTraceListener.dll", "System.Text.Encodings.Web.dll", "System.Reflection.Extensions.dll"]
2024-04-20T18:33:52 - MEF Default Assemblies: /home/emik/.dotnet/tools/.store/csharprepl/0.6.7/csharprepl/0.6.7/tools/net8.0/any/Microsoft.CodeAnalysis.Workspaces.dll, /home/emik/.dotnet/tools/.store/csharprepl/0.6.7/csharprepl/0.6.7/tools/net8.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll, /home/emik/.dotnet/tools/.store/csharprepl/0.6.7/csharprepl/0.6.7/tools/net8.0/any/Microsoft.CodeAnalysis.Features.dll, /home/emik/.dotnet/tools/.store/csharprepl/0.6.7/csharprepl/0.6.7/tools/net8.0/any/Microsoft.CodeAnalysis.CSharp.Features.dll
2024-04-20T18:33:52 - Background initialization complete
2024-04-20T18:33:52 - Warm-up Starting
2024-04-20T18:33:54 - Warm-up Complete
2024-04-20T18:33:56 - Unhandled Exception: System.InvalidOperationException: Unexpected value 'Submission' of type 'Microsoft.CodeAnalysis.TypeKind'
   at Microsoft.CodeAnalysis.CSharp.Binder.<BindObjectCreationExpression>g__bindObjectCreationExpression|421_0(ObjectCreationExpressionSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindObjectCreationExpression(ObjectCreationExpressionSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.<BindExpressionInternal>g__bindExpressionInternal|325_0(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, BindingDiagnosticBag diagnostics, BindValueKind valueKind)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindRValueWithoutTargetType(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean reportNoTargetType)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, SegmentedList`1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(SyntaxNode syntax, TextSpan textSpan, SemanticModel semanticModel, ClassificationOptions options, SegmentedList`1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNodeOrToken(SyntaxNodeOrToken nodeOrToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(SemanticModel semanticModel, ImmutableArray`1 textSpans, SegmentedList`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ClassificationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassifications(SemanticModel semanticModel, ImmutableArray`1 textSpans, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, SegmentedList`1 result, ClassificationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.SyntaxClassificationServiceExtensions.AddSemanticClassifications(ISyntaxClassificationService classificationService, SemanticModel semanticModel, TextSpan textSpan, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, SegmentedList`1 result, ClassificationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.Classifier.GetClassifiedSpans(SolutionServices services, Project project, SemanticModel semanticModel, TextSpan textSpan, ClassificationOptions options, Boolean includedEmbeddedClassifications, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.Classifier.GetClassifiedSpans(SolutionServices services, Project project, SemanticModel semanticModel, TextSpan textSpan, ClassificationOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.Classifier.GetClassifiedSpansAsync(Document document, TextSpan textSpan, CancellationToken cancellationToken)
   at CSharpRepl.Services.SyntaxHighlighting.SyntaxHighlighter.HighlightAsync(Document document) in /_/CSharpRepl.Services/SyntaxHighlighting/SyntaxHighlighter.cs:line 47
   at CSharpRepl.Services.Roslyn.RoslynServices.SyntaxHighlightAsync(String text) in /_/CSharpRepl.Services/Roslyn/RoslynServices.cs:line 216
   at CSharpRepl.PrettyPromptConfig.CSharpReplPromptCallbacks.HighlightCallbackAsync(String text, CancellationToken cancellationToken) in /_/CSharpRepl/CSharpReplPromptCallbacks.cs:line 137
   at PrettyPrompt.Highlighting.SyntaxHighlighter.HighlightAsync(String input, CancellationToken cancellationToken)
   at PrettyPrompt.Prompt.RenderSyntaxHighlightedOutput(Renderer renderer, CodePane codePane, OverloadPane overloadPane, CompletionPane completionPane, KeyPress key, String inputText, PromptResult result)
   at PrettyPrompt.Prompt.ReadLineAsync()
   at CSharpRepl.ReadEvalPrintLoop.RunAsync(Configuration config) in /_/CSharpRepl/ReadEvalPrintLoop.cs:line 51
   at CSharpRepl.Program.Main(String[] args) in /_/CSharpRepl/Program.cs:line 71
   at CSharpRepl.Program.Main(String[] args) in /_/CSharpRepl/Program.cs:line 77
   at CSharpRepl.Program.<Main>(String[] args)
```
</details>

**Comment by Rekkonnect** [comment]
In 0.6.8 this is no longer present, leaving open for confirmation

**Comment by waf** [comment]
Confirmed, thanks @Rekkonnect and @Emik03!
