### ISSUE TITLE
Windows 7 SP1 - Fail when trying to execute

### ISSUE THREAD

**Issue by Ribeiro** [waf/CSharpRepl#37]
### Version

0.3.3

### What happened?

When I try to run charprepl I got:

Unhandled exception. System.InvalidOperationException: failed to set output console mode, error code: 87
   at PrettyPrompt.Consoles.SystemConsole.InitVirtualTerminalProcessing()
   at PrettyPrompt.Prompt..ctor(String persistentHistoryFilepath, PromptCallbacks callbacks, IConsole console)
   at CSharpRepl.Program.Main(String[] args) in C:\Users\will.fuqua\source\repos\CSharpRepl\CSharpRepl\Program.cs:line 38
   at CSharpRepl.Program.<Main>(String[] args)

**Comment by waf** [comment]
Hi, thanks for reporting! This tool requires Windows 10 version 1511 (build number 10586, released in November 2016) as the minimum version. It's because it uses ANSI escape sequence support released in that version. I'll update the readme to mention that.

**Comment by Ribeiro** [comment]
Oh ok then. Thank you for your prompt reply. It seems I'll have to drop Win 7 =(
