### ISSUE TITLE
 One or more errors occurred.

### ISSUE THREAD

**Issue by llp1520** [waf/CSharpRepl#383]
### Version

C# REPL 0.6.7

### What happened?

Something went wrong :(
One or more errors occurred. (Could not load file or assembly 'NuGet.Common, Version=6.9.1.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 系统找不到指定的文件。)

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Common, Version=6.9.1.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 系统找不到指定的文 件。
File name: 'NuGet.Common, Version=6.9.1.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at CSharpRepl.Services.Nuget.NugetPackageInstaller..ctor(IConsoleEx console, Configuration configuration)
   at CSharpRepl.Services.Roslyn.MetadataResolvers.NugetPackageMetadataResolver..ctor(IConsoleEx console, Configuration configuration) in /_/CSharpRepl.Services/Roslyn/MetadataResolvers/NugetPackageMetadataResolver.cs:line 25
   at CSharpRepl.Services.Roslyn.Scripting.ScriptRunner..ctor(WorkspaceManager workspaceManager, CSharpCompilationOptions compilationOptions, AssemblyReferenceService referenceAssemblyService, IConsoleEx console, Configuration configuration) in /_/CSharpRepl.Services/Roslyn/Scripting/ScriptRunner.cs:line 50
   at CSharpRepl.Services.Roslyn.RoslynServices.<>c__DisplayClass20_1.<.ctor>b__1() in /_/CSharpRepl.Services/Roslyn/RoslynServices.cs:line 94
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CSharpRepl.Services.Roslyn.RoslynServices.EvaluateAsync(String input, String[] args, CancellationToken cancellationToken) in /_/CSharpRepl.Services/Roslyn/RoslynServices.cs:line 108
   at CSharpRepl.ReadEvalPrintLoop.RunAsync(Configuration config) in /_/CSharpRepl/ReadEvalPrintLoop.cs:line 81
   at CSharpRepl.Program.Main(String[] args) in /_/CSharpRepl/Program.cs:line 71
   at CSharpRepl.Program.Main(String[] args) in /_/CSharpRepl/Program.cs:line 77
   at CSharpRepl.Program.<Main>(String[] args)

**Comment by llp1520** [comment]
my sdk is .net9 ,because  i use vs preview.when i download .net8 sdk ,the error has missed
