### ISSUE TITLE
System.InvalidOperationException: failed to set output console mode, error code: 87

### ISSUE THREAD

**Issue by iamkylescode** [waf/CSharpRepl#42]
### Version

0.3.3

### What happened?

I try to start csharprepl from command prompt and I get:

```
Unhandled exception. System.InvalidOperationException: failed to set output console mode, error code: 87
   at PrettyPrompt.Consoles.SystemConsole.InitVirtualTerminalProcessing()
   at PrettyPrompt.Prompt..ctor(String persistentHistoryFilepath, PromptCallbacks callbacks, IConsole console)
   at CSharpRepl.Program.Main(String[] args) in C:\Users\will.fuqua\source\repos\CSharpRepl\CSharpRepl\Program.cs:line 3
8
   at CSharpRepl.Program.<Main>(String[] args)
```

I noticed someone else had reported this a few days ago, but their issue was that they were running it on Windows 7. In my case, I am running Windows 10 Build 19043.1237, but also getting this exception.

**Comment by iamkylescode** [comment]
Some additional info from dotnet --info output that you might find helpful:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by waf** [comment]
Thanks for reporting this! It's good to build up a list of these sort of issues. Could you please check the following?

1. In the command prompt properties, can you please check if [Legacy Mode is disabled](https://docs.microsoft.com/en-us/windows/console/legacymode)? CSharpRepl won't work with Legacy Mode
1. If that's not the issue, could you also check if it works on [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701#activetab=pivot:overviewtab)? CSharpRepl works on the command prompt, but this would help narrow down the issue.

**Comment by iamkylescode** [comment]
Thank you for your suggestion. Legacy Mode was enabled. Once I disabled this and restarted command prompt, the repl worked! And, it does work in Terminal as well (which is where I will use it most of the time :-D)

**Comment by waf** [comment]
Glad to hear it! I'll keep this bug open for now; I'll improve the error message to include this information. Thanks for opening it.
