### ISSUE TITLE
Referencing an assembly in .NET 6.0 fails with System.ArgumentException

### ISSUE THREAD

**Issue by Ruin0x11** [waf/CSharpRepl#44]
### Version

6d462626afd8e3341567d1a4a074586e3121d215

### What happened?

Related to #8.

The fix for that issue (#9) wasn't applied everywhere, and the version string parsing fails again in `AssemblyReferenceMetadataResolver`.

https://github.com/waf/CSharpRepl/blob/905caf3484fc47a8f70af456111ecfeb71f5a191/CSharpRepl.Services/Roslyn/MetadataResolvers/AssemblyReferenceMetadataResolver.cs#L67-L69

```
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at CSharpRepl.Services.Roslyn.MetadataResolvers.AssemblyReferenceMetadataResolver.LoadSharedFramework(ImmutableArray`1 references)
   at CSharpRepl.Services.Roslyn.MetadataResolvers.AssemblyReferenceMetadataResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties, MetadataReferenceResolver compositeResolver)
   at CSharpRepl.Services.Roslyn.MetadataResolvers.CompositeMetadata
ReferenceResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveReferenceDirective(String reference, Location location, TCompilation compilation)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations)
   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostic
s)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.get_SourceModule()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SimpleProgramNamedTypeSymbol.GetSimpleProgramNamedTypeSymbol(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SimpleProgramNamedTypeSymbol.GetSimpleProgramEntryPoint(CSharpCompilation compilation)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetEntryPointAndDiagnostics(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetEntryPoint(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetEntryPoint(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.ScriptB
uilder.Build[T](Compilation compilation, DiagnosticBag diagnostics, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at CSharpRepl.Services.Roslyn.Scripting.ScriptRunner.EvaluateStringWithStateAsync(String text, ScriptState`1 state, InteractiveAssemblyLoader assemblyLoader, ScriptOptions scriptOptions, String[] args, CancellationToken cancellationToken)
\ScriptRunner.cs:line 116
   at CSharpRepl.Services.Roslyn.Scripting.ScriptRunner.RunCompilation(String text, String[] args, CancellationToken cancellationToken)
```

**Comment by Ruin0x11** [comment]
Yes, this happens when the runtime is .NET 6.0, and applying the fix in #9 to the referenced location solves the issue for me.

This is an excellent library, by the way. I was able to reuse some of the existing display code to create an SDL-based renderer for my game development project. Thanks for all your hard work.
