### ISSUE TITLE
CSharpRepl is picking incorrect platform while referencing nuget

### ISSUE THREAD

**Issue by kindermannhubert** [waf/CSharpRepl#58]
### Version

0.3.5

### What happened?

Using ```System.Management``` nuget throws
```
System.PlatformNotSupportedException: System.Management currently is only supported for Windows desktop applications.
   at System.Management.ManagementOptions..ctor()
   at System.Management.ConnectionOptions..ctor()
   at CsiUtils.UserCredentials.GetSelf()
```
E.g. this code
```C#
new System.Management.ConnectionOptions();
```
works while running from console app, but throws if run from CSharpRepl.

```System.Management``` is implemented only for Windows. There are two base versions:
.nuget\packages\system.management\6.0.0\lib\net6.0 (everything throw PlatformNotSupportedException)
.nuget\packages\system.management\6.0.0\runtimes\win\lib\net6.0 (actual win implementation)

I've located loaded assembly after
```c#
#r "nuget: System.Management"
```
in temp directory where referenced copy is and it definitely is wrong implementation (=same size as in .nuget\packages\system.management\6.0.0\lib\net6.0).

**Comment by kindermannhubert** [comment]
This could be helpful: https://github.com/NuGet/Home/issues/10914
